### ISSUE TITLE
Not working with Hibernate ORM 5.5

### ISSUE THREAD

**Issue by DavideD** [hibernate/hibernate-reactive#384]
The API has changed in 5.5

```
/home/runner/work/hibernate-reactive/hibernate-reactive/hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/ReactiveLoaderBasedResultSetProcessor.java:140: error: cannot find symbol

> Task :hibernate-reactive-core:compileJava
			GraphImplementor<?> fetchGraphLoadContextToRestore = session.getFetchGraphLoadContext();
			                                                            ^
  symbol:   method getFetchGraphLoadContext()
  location: variable session of type SharedSessionContractImplementor
/home/runner/work/hibernate-reactive/hibernate-reactive/hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/ReactiveLoaderBasedResultSetProcessor.java:146: error: cannot find symbol
					session.setFetchGraphLoadContext( fetchGraphLoadContextToRestore );
					       ^
  symbol:   method setFetchGraphLoadContext(GraphImplementor<CAP#1>)
  location: variable session of type SharedSessionContractImplementor
  where CAP#1 is a fresh type-variable:
    CAP#1 extends Object from capture of ?
Note: Some input files use or override a deprecated API.
```

**Comment by gavinking** [comment]
Surely a consequence of https://github.com/hibernate/hibernate-orm/pull/3548

**Comment by DavideD** [comment]
Yep

**Comment by DavideD** [comment]
Possible fix for when we upgrade to 5.5 or the issue is backported to 5.4: https://github.com/DavideD/hibernate-reactive/commit/05c410850aa741350b49746328f3a9f8e5906258

**Comment by DavideD** [comment]
> Possible fix for when we upgrade to 5.5 or the issue is backported to 5.4: [DavideD@05c4108](https://github.com/DavideD/hibernate-reactive/commit/05c410850aa741350b49746328f3a9f8e5906258)

It is going to be backported

**Comment by DavideD** [comment]
This is fixed now by https://github.com/hibernate/hibernate-reactive/pull/391
I'm going to close the issue once I have included ORM 5.5 in the workflows
