### ISSUE TITLE
Failed on createQuery with exception java.lang.NoSuchMethodError: org/hibernate/query/internal/QueryImpl.<init>

### ISSUE THREAD

**Issue by yaakov-berkovitch** [hibernate/hibernate-reactive#746]
Hi,

I just move to release candidate 4 (1.0.0.CR4), and the same simple query that was working with 1.0.0.CR3 failed now with the following exception:
```
18:34:55.480 [vert.x-eventloop-thread-0] DEBUG org.hibernate.hql.internal.ast.util.JoinProcessor - Using FROM fragment [device device0_]
18:34:55.480 [vert.x-eventloop-thread-0] DEBUG org.hibernate.hql.internal.antlr.HqlSqlBaseWalker - select >> end [level=1, statement=select]
18:34:55.481 [vert.x-eventloop-thread-0] DEBUG org.hibernate.hql.internal.ast.QueryTranslatorImpl - --- SQL AST ---
 \-[SELECT] QueryNode: 'SELECT'  querySpaces (device)
    +-[SELECT_CLAUSE] SelectClause: '{derived select clause}'
    |  +-[SELECT_EXPR] SelectExpressionImpl: 'device0_.id as id1_0_' {FromElement{explicit,not a collection join,not a fetch join,fetch non-lazy properties,classAlias=null,role=null,tableName=device,tableAlias=device0_,origin=null,columns={,className=com.algosec.objectflow.objectimporter.model.Device}}}
    |  \-[SQL_TOKEN] SqlFragment: 'device0_.created_at as created_2_0_, device0_.updated_at as updated_3_0_, device0_.version as version4_0_, device0_.brand as brand5_0_, device0_.display_name as display_6_0_, device0_.name as name7_0_, device0_.uuid as uuid8_0_'
    \-[FROM] FromClause: 'FROM' FromClause{level=1, fromElementCounter=1, fromElements=1, fromElementByClassAlias=[], fromElementByTableAlias=[device0_], fromElementsByPath=[], collectionJoinFromElementsByPath=[], impliedElements=[]}
       \-[FROM_FRAGMENT] FromElement: 'device device0_' FromElement{explicit,not a collection join,not a fetch join,fetch non-lazy properties,classAlias=null,role=null,tableName=device,tableAlias=device0_,origin=null,columns={,className=com.algosec.objectflow.objectimporter.model.Device}}

18:34:55.481 [vert.x-eventloop-thread-0] DEBUG org.hibernate.hql.internal.ast.ErrorTracker - throwQueryException() : no errors
18:34:55.484 [vert.x-eventloop-thread-0] DEBUG org.hibernate.hql.internal.ast.QueryTranslatorImpl - HQL: FROM com.algosec.objectflow.objectimporter.model.Device
18:34:55.484 [vert.x-eventloop-thread-0] DEBUG org.hibernate.hql.internal.ast.QueryTranslatorImpl - SQL: select device0_.id as id1_0_, device0_.created_at as created_2_0_, device0_.updated_at as updated_3_0_, device0_.version as version4_0_, device0_.brand as brand5_0_, device0_.display_name as display_6_0_, device0_.name as name7_0_, device0_.uuid as uuid8_0_ from device device0_
18:34:55.484 [vert.x-eventloop-thread-0] DEBUG org.hibernate.hql.internal.ast.ErrorTracker - throwQueryException() : no errors
java.util.concurrent.CompletionException: java.lang.NoSuchMethodError: org/hibernate/query/internal/QueryImpl.<init>(Lorg/hibernate/engine/spi/SharedSessionContractImplementor;Lorg/hibernate/engine/query/spi/HQLQueryPlan;Ljava/lang/String;)V (loaded from file:/C:/Users/yaakov.berkovitch/.m2/repository/org/hibernate/hibernate-core/5.4.28.Final/hibernate-core-5.4.28.Final.jar by jdk.internal.loader.ClassLoaders$AppClassLoader@1fa9057e) called from class org.hibernate.reactive.session.impl.ReactiveQueryImpl (loaded from file:/C:/Users/yaakov.berkovitch/.m2/repository/org/hibernate/reactive/hibernate-reactive-core/1.0.0.CR4/hibernate-reactive-core-1.0.0.CR4.jar by jdk.internal.loader.ClassLoaders$AppClassLoader@1fa9057e).
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1081)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1085)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at org.hibernate.reactive.stage.impl.StageSessionFactoryImpl.lambda$null$0(StageSessionFactoryImpl.java:52)
	at org.hibernate.reactive.stage.impl.StageSessionFactoryImpl$$Lambda$214/000000000000000000.handle(Unknown Source)

```

The code looks like:
```
        sessionFactory.withSession(
                session -> session.createQuery("FROM Device", Device.class)
                        .getResultList().toCompletableFuture()
                        .thenApply(rows -> {
                            Collection<Device> result = new ArrayList<>(rows.size());
                            rows.forEach(row -> {
                                result.add((Device) row);
                            });
                            return result.stream();
                        })
        ).exceptionally(throwable -> {
            throwable.printStackTrace();
            return null;
        });
```
Dependencies:
- Hibernate Reactive version 1.0.0.CR4
- io.vertx:vertx-pg-client:4.0.3
- io.vertx:vertx-core:4.0.3
- Spring boot
- Junit
- Postgres
- Java-11
-

**Comment by DavideD** [comment]
Hibernate Reactive 1.0.0.CR4 won’t work with versions of Hibernate ORM
older than 5.4.31.Final.

Sorry for the inconvenience.

**Comment by DavideD** [comment]
The release post contains a couple more details about it:
https://in.relation.to/2021/04/30/hibernate-reactive-1_0_0_CR4/

**Comment by gavinking** [comment]
It's a bother for sure, but in general HR is always going to be pretty tightly coupled to core, so I think we're just going to have to live with this sort of problem.

**Comment by yaakov-berkovitch** [comment]
Thanks. I will adjust the dependencies. BTW, till now I didn't put it in my gradle file because I supposed that the Hibernate reactive depends on the correct Hibernate ORM, but it seems that it's not the case.
Thanks.

**Comment by gavinking** [comment]
@yaakov-berkovitch not quite sure what you mean. The dependency info looks correct here:

https://mvnrepository.com/artifact/org.hibernate.reactive/hibernate-reactive-core/1.0.0.CR4
