### PR TITLE
[wip/3.2] Upgrade to Hibernate ORM 7.2.9.Final

### PR DESCRIPTION
**Pull request by dreab8**
Changes in ORM 7.2.9.Final introduced by https://github.com/hibernate/hibernate-orm/pull/12104 cause compilation errors in Reactive

### CODE REVIEW

File: hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/exec/internal/ReactiveJdbcSelectWithActions.java [hunk 1]
```diff
@@ -95,35 +97,30 @@ public CompletionStage<Void> reactivePerformPreActions(
...
 					}
-			).thenAccept( unused -> {
-				if ( loadedValuesCollector != null ) {
-					loadedValuesCollector.clear();
-				}
-			} );
+			);
 		}
 		else {
-			if ( loadedValuesCollector != null ) {
```
Comment (DavideD) [inline hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/exec/internal/ReactiveJdbcSelectWithActions.java:117]: Why did youremove all this block with the clear of Collector? It seems it still exists in ORM

Comment (dreab8) [reply hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/exec/internal/ReactiveJdbcSelectWithActions.java:117]: it has been removed https://github.com/hibernate/hibernate-orm/pull/12104/changes#diff-ce216ff88e98604147d5409cd964ff234a88ae4d026882b8f335bf20b3241bc3L127

Comment (DavideD) [reply hibernate-reactive-core/src/main/java/org/hibernate/reactive/sql/exec/internal/ReactiveJdbcSelectWithActions.java:117]: Nevermind, I was looking at the wrong ORM version
